version: '3.7'

services:
  redis_queue:
    image: redis:5.0.8-buster
    ports:
      - "6379:6379"
  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    depends_on:
      - redis_queue
    command: rq worker --url redis://redis_queue:6379/0 task-queue
    volumes:
      - ./instance:/home/appuser/worker/instance
    env_file:
      - ./worker/env/worker.dev.env
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile.dev
    command: flask run --host 0.0.0.0
    volumes:
      - ./:/home/appuser
    ports:
      - 5000:5000
    env_file:
      - ./app/env/dev.env
